version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: scrapy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: msql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  scrapy:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=msql_password
      - MYSQL_DATABASE=scrapy_data

volumes:
  mysql_data:
